### ISSUE TITLE
Retos Python Study Group 

### ISSUE THREAD

**Issue by jevillanueva** [Aivan-17/psg-example#1]
Hola!

Veo que aun faltan retos del python study group....  

Me gustaria invitarte a que continues 😄 

Aquí encontrarás todas las sesiones y sus retos  https://study.pylapaz.org/

No te desanimes!! estare atento a tus retos, animo!!!

**Comment by Aivan-17** [comment]
hola , si disculpa estuve con muchas cosas pendientes que ya las complete ,
en el transcurso de la semana me pondre al dia mejor agradecerte por el
seguimiento
